version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command: uwsgi --uid nobody --http 0.0.0.0:8000 --wsgi-file src/test.py
    command: uwsgi --uid nobody --uwsgi-socket 0.0.0.0:8000 --wsgi-file src/test.py
    volumes:
      - .:/code
